# Docker compose file for FSO exercises 12.x

name: todoapp

networks:
  todoapp:


volumes:
  mongo_data:


services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8888:80
    container_name: reverse-proxy
    depends_on:
      - todoapp
    networks:
      - todoapp

  todoapp:
    depends_on:
      - todoback
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile-build
      args:
        BACKEND_URL: 'http://localhost:8888/api'
    networks:
      - todoapp
    environment:
      VITE_BACKEND_URL: 'http://localhost:8888/api'

  todoback:
    depends_on:
      - mongo
      - redis
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile-build
    networks:
      - todoapp
    environment:
      MONGO_URL: 'mongodb://the_username:the_password@todoapp-mongo-1:27017/the_database'
      REDIS_URL: 'redis://todoapp-redis-1:6379'

  mongo:
    image: mongo
    networks:
      - todoapp
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db

  redis:
    image: redis
    networks:
      - todoapp
    command: [ 'redis-server', '--appendonly', 'yes' ] # Overwrite the CMD
    volumes:
      - ./redis_data:/data
