# Docker compose file for FSO exercises 12.x
# Support development inside a container
name: tododev

networks:
  tododev:


volumes:
  mongo_dev:


services:

  todoapp:
    profiles:
      - dev
    command: npm run dev -- --host
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile-dev
    networks:
      - tododev
    ports:
      - 5173:5173
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      VITE_BACKEND_URL: 'http://localhost:8888/api'

  todoback:
    profiles:
      - dev
    depends_on:
      - mongo
      - redis
    command: npm run dev
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: Dockerfile-dev
    networks:
      - tododev
    ports:
      - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      MONGO_URL: 'mongodb://the_username:the_password@tododev-mongo-1:27017/the_database'
      REDIS_URL: 'redis://tododev-redis-1:6379'

  nginx:
    profiles:
      - dev
    depends_on:
      - todoapp
      - todoback
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8888:80
    container_name: reverse-proxy
    networks:
      - tododev

  # databases should be always available so not in a profile
  mongo:
    image: mongo
    networks:
      - tododev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_dev:/data/db

  redis:
    image: redis
    networks:
      - tododev
    command: [ 'redis-server', '--appendonly', 'yes' ] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data
